server:
  port: 8080

spring:
  application:
    name: employee-payroll-application
  datasource:
    url: jdbc:h2:mem:employeeDb
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

# kafka properties
kafka:
  bootstrap-server: localhost:9092
  topic-name: employee-payroll-topic
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    group-id: payroll-group
    auto-offset-reset: latest

